// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("https://www.service.nsw.gov.au/");
    driver.manage().window().setSize(new Dimension(1936, 1066));
    driver.findElement(By.linkText("Driving and transport")).click();
    driver.findElement(By.cssSelector(".tile-grid__item:nth-child(3) .tile__heading")).click();
    driver.findElement(By.cssSelector(".tile-grid__item:nth-child(6) .tile__heading")).click();
    driver.findElement(By.linkText("Find a service centre")).click();
    driver.findElement(By.id("locatorTextSearch")).click();
    driver.findElement(By.id("locatorTextSearch")).sendKeys("sydney 2000");
    {
      String value = driver.findElement(By.id("locatorTextSearch")).getAttribute("value");
      assertThat(value, is("sydney 2000"));
    }
    driver.findElement(By.cssSelector(".autocomplete__option:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".button--primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".button--primary > svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".button--primary > svg")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".button--primary > svg"));
      assert(elements.size() > 0);
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      List<WebElement> elements = driver.findElements(By.linkText("Haymarket Service Centre"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Haymarket Service Centre")).click();
    {
      List<WebElement> elements = driver.findElements(By.linkText("Marrickville Service Centre"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.linkText("Marrickville Service Centre")).click();
    assertThat(driver.findElement(By.id("page-title")).getText(), is("Marrickville Service Centre"));
  }
}
